version: '3.9'

services:
  quarkus-service:
    image: maven
    container_name: quarkus-dev
    env_file:
     - ./.env
    mem_limit: 512m
    volumes:
      - "./:/app"
      - "~/.m2:/root/.m2"
    ports:
      - "8080:8080"
    working_dir: /app
    command: "mvn quarkus:dev"  